spring.application.name=messaverde-tiendamuebles-servicesdswii

spring.datasource.url=jdbc:mysql://localhost:3306/db_dswii_tiendamuebles
spring.datasource.username=root
spring.datasource.password=root

